# ----------- CONFIGURABLE START -----------
title:            "DHN GROUP|Bất Động Sản Kon Tum"
description:      "Sàn giao dịch bất động sản tại thành phố Kon Tum"
url:              https://dhngroup.github.io # DHN GROUP
signoff:          "DHN GROUP"
facebook_appid:   #dhnrealty
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "dhnpage:num"
gems: [jekyll-paginate]
links:
  - name:         Trang đầu
    url:          /
    external:     false
  - name:         Dự Án
    url:          /book
    external:     false
  - name:         Tin Tức
    url:          /road
    external:     false
  - name:         Lưu Trữ
    url:          /archives
    external:     false
  - name:         Tag
    url:          /tags
    external:     false
  - name:         Giới Thiệu
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
